### ISSUE TITLE
Предположительно, неправильный путь к mapsoft2-libs

### ISSUE THREAD

**Issue by ioctl-user** [slazav/mapsoft2#50]
1) В корневой папке лежит файл modules.tar, который хочется распаковать, вместо того, чтобы скачать modules.

2) При попытке скачать модули командой "git submodule update --init --recursive" появляется ошибка -- ругается на путь "github:slazav/mapsoft2-libs". Если его заменить на "https://github.com/slazav/mapsoft2-libs.git" в файле .git/config , то выкачивается нормально.

Я с модулями git мало знаком, может что-то не так делаю.

**Comment by slazav** [comment]
1. Этот файл сделан только для сборок в Altlinux, который не хочет git submodules. Идея в том, что он будет обновляться и коммитится перед сборкой новой версии. В остальных случаях не надо его использовать.

2. Прописал туда что-то более разумное (git@github.com:...).

**Comment by ioctl-user** [comment]
По всей видимости адрес git@github.com:slazav/mapsoft2-libs подразумевает наличие неких заранее загруженных ключей на github: https://github.com/settings/keys . Без них не даёт скачать.

**Comment by slazav** [comment]
Мне-то хочется и коммитить по этому адресу...
Пока исправил на https, посмотрим, удобно ли так будет.
