### ISSUE TITLE
Ошибка сборки теста io_png

### ISSUE THREAD

**Issue by ioctl-user** [slazav/mapsoft2#54]
Подмодули были скачаны гитом.

```## Running test: io_jpeg.test
g++ -I/usr/include/libpng16  -std=gnu++11 -Werror=return-type -O2 -fPIC -I..   -c -o io_png.test.o io_png.test.cpp
g++   io_png.test.o colors.o image.o image_colors.o io.o io_gif.o io_jpeg.o io_png.o io_tiff.o ../filename/filename.a ../geo_tiles/geo_tiles.a ../geom/geom.a ../downloader/downloader.a ../cache/cache.a ../getopt/getopt.a ../opt/opt.a ../err/err.a  -lpthread -ljpeg -ljansson -ltiff -lpng16 -lz -lcurl -lgif  -o io_png.test
## Running test: io_png.test
Error: Can't open file: test_png/blue.png
make[2]: *** [../Makefile.inc:92: io_png.test.passed] Ошибка 1
make[2]: выход из каталога «/tmp/mapsoft2/modules/image»
```

**Comment by slazav** [comment]
Да, в какой-то момент была забыта тестовая картинка. Вроде, исправлено в ee163e800df807b2d9b922b76df82f44d6ea206c

**Comment by ioctl-user** [comment]
Скачивал буквально час назад, проблема была. Но при распаковке из архива modules.tar всё нормально. Наверно, где-то что-то рассинхронизировалось.

**Comment by slazav** [comment]
modules.tar вообще не надо трогать, он точно старый (соответствует последней версии, собранной в Altlinux, и используется только для этого). Там этой ошибки еще нет.

Проблема, кажется, в том, что актуальное состояние modules не закоммичено в mapsoft2. И git submodule update
ставит modules в какой-то прошлый коммит. Вроде, помогает зайти в modules и сказать git checkout master.

**Comment by slazav** [comment]
Ну и теперь я все закоммитил, так что pull + submodule update в mapsoft2 тоже должно сработать.
