### ISSUE TITLE
Создание папок в ms2mapdb

### ISSUE THREAD

**Issue by ioctl-user** [slazav/mapsoft2#58]
Судя по Makefile в map_podm, папка TILES создаётся командо mkdir, а ms2mapdb это делать не умеет.

При попыткы автоматически разложить плитки по папкам, например, при запуске ms2mapdb с ключём --out "TILES/{z}/{x}-{y}.png", выдаётся следующая ошибка:

```
Error: Can't open file: TILES/14/9932-4991.png
make: *** [Makefile:154: tiles] Ошибка 1
```
Хорошо бы это как-то автоматизировать. По умолчанию, или с добавлением ключика.

Уточню, папки TILES/14/ изначально не было. В случае параметра Z это можно сделать вручную, но если надо сделать что-то вроде --out "TILES/{z}/{x}/{y}.png , то будут трудности.

**Comment by slazav** [comment]
Да, буду делать!

**Comment by slazav** [comment]
Сделано!
ac0548576ac61cf4a1d3bf6d966ddc1801a44f73
(основное изменение - в modules/)
