### ISSUE TITLE
Сборочные тесты требуют уже установленный пакет mapsoft2

### ISSUE THREAD

**Issue by ioctl-user** [slazav/mapsoft2#63]
Тест test_convert падает из-за того, что пакет mapsoft2 не установлен в систему. Сборка на чистой системе невозможна.

Первое сообщение об ошибке.

```## Running test: test_convert
ERROR (./ms2vmapdb import -o tmp missing.vmap):
  exp:
Error: db_simple: tmp.vmap2db: No such file or directory
  res:
Error: can't open file: /usr/share/mapsoft2/types.cfg
make[1]: *** [../../modules/Makefile.inc:110: make_tests] Ошибка 1
```

Проблема в каждой из следующих строках теста:

```
assert_cmd "$P import -o tmp missing.vmap" "Error: db_simple: tmp.vmap2db: No such file or directory" 1
assert_cmd "$P import -o tmp missing.vmap" "Error: can't open file: missing.vmap" 1
assert_cmd "$P export tmp -o tmp.vmap2" "" 0
assert_diff $TESTDIR/out.vmap2 tmp.vmap2
assert_cmd "$P export tmp -o tmp.vmap -q 1" "" 0
assert_diff $TESTDIR/out.vmap tmp.vmap
```

Аналогичная зависимость от установленного в систему файла есть в тестах test_update_labels и test_crop.

Возможный вариант решения проблемы: добавить к программам опциональный параметр, который позволит указывать путь к файлам конфигурации, или копировать файлы конфигурации в папку, откуда запускаются тесты. Тогда при сборке можно запускать тесты с файлами из скачанного репозитория.

**Comment by slazav** [comment]
Вроде, это уже исправлено
