### ISSUE TITLE
conv_geo test failed

### ISSUE THREAD

**Issue by sikmir** [slazav/mapsoft2#64]
```sh
mapsoft2> ## Running test: conv_geo.test
mapsoft2> Error: assert_err: conv_geo.test.cpp:224: error is not thrown:
mapsoft2> command: cnv1.frw(p1)
mapsoft2> expected error: Can't convert coordinates: Point outside of projection domain
```
mapsoft2 2.2

**Comment by slazav** [comment]
What is libproj version?
The change happened between proj-9.1.0 and 9.2.1. I updated the code here:
https://github.com/slazav/mapsoft2-libs/commit/1e52a7538c292bbe977574dc4980fdac297979fe

It could be that some earlier proj version number should be put in this test.

**Comment by sikmir** [comment]
> What is libproj version?

9.2.0

**Comment by slazav** [comment]
OK, I'm updating the test.

**Comment by sikmir** [comment]
Fixed in https://github.com/slazav/mapsoft2-libs/commit/9300f93e171769bbf8710d9dfa5f2724b7b6142d
