### ISSUE TITLE
Build with clang failed

### ISSUE THREAD

**Issue by sikmir** [slazav/mapsoft2#68]
```sh
mapsoft2> In file included from ./io.h:7:
mapsoft2> ./image_r.h:52:41: error: cannot initialize return object of type 'unsigned char *' with an rvalue of type 'element_type *' (aka 'unsigned char (*)[]')
mapsoft2>     unsigned char *data() const {return data_.get();}
mapsoft2>                                         ^~~~~~~~~~~
mapsoft2> ./image_r.h:88:17: error: no matching conversion for functional-style cast from 'unsigned char *' to 'std::shared_ptr<unsigned char[]>'
mapsoft2>         data_ = std::shared_ptr<unsigned char[]>(new unsigned char[dsize()]);
mapsoft2>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by slazav** [comment]
Can't reproduce with clang++18.1.8.
I noticed that shared_ptr with array type is marked as C++17 feature.
Does `CXX=clang++ CXXFLAGS=-std=gnu++17 make` works?

**Comment by slazav** [comment]
please also try recent commit in mapsoft2-libs

**Comment by sikmir** [comment]
> Can't reproduce with clang++18.1.8. I noticed that shared_ptr with array type is marked as C++17 feature. Does `CXX=clang++ CXXFLAGS=-std=gnu++17 make` works?

clang 16.0.6 on macOS. Yes, `-std=c++17` solves problem.

**Comment by sikmir** [comment]
> please also try recent commit in mapsoft2-libs

Yes, it works as well (without `-std=c++17`)
