### ISSUE TITLE
Ошибки многопоточной сборки

### ISSUE THREAD

**Issue by ioctl-user** [slazav/mapsoft2#69]
Программа не собирается в несколько потоков. Видимо, не до конца прописаны зависимости между модулями в Makefile.

Некоторые ошибки при запуске с make -j 8 :

```
make[2]: вход в каталог «/home/build/misc/map_podm/mapsoft2/modules/err»
make[2]: выход из каталога «/home/build/misc/map_podm/mapsoft2/modules/err»
make[2]: вход в каталог «/home/build/misc/map_podm/mapsoft2/modules/time_fmt»
g++   err.test.o    -o err.test
## Running test: err.test
/bin/sh: строка 1: ./err.test: Отказано в доступе
make[2]: *** [../Makefile.inc:135: err.test.passed] Ошибка 126
make[2]: выход из каталога «/home/build/misc/map_podm/mapsoft2/modules/err»
make[1]: *** [../../modules/Makefile.inc:105: make_deps] Ошибка 2
make[1]: выход из каталога «/home/build/misc/map_podm/mapsoft2/programs/ms2render»

...

/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../lib/Scrt1.o: в функции «_start»:   
(.text+0x1b): undefined reference to `main'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make[2]: *** [<встроенное>: sizecache.test] Ошибка 1
make[2]: выход из каталога «/home/build/misc/map_podm/mapsoft2/modules/cache»
make[1]: *** [../../modules/Makefile.inc:105: make_deps] Ошибка 2

...

g++ -std=gnu++11 -I/usr/include/libxml2 -I/usr/include/libpng16 -Werror=return-type -Wstrict-aliasing=2 -O2 -fPIC -g -I../../modules    -c -o ms2tiles.o ms2tiles.cpp
make[1]: *** Нет правила для сборки цели «../../modules/geo_data/geo_data.a», требуемой для «ms2tiles».  Останов.

...

# Running test: getopt.test
ERROR:
  args: "-v -I"
  exp:  "Error: missing argument: -I"
  res:  ""
make[2]: *** [../Makefile.inc:135: getopt.test.passed] Ошибка 1
make[2]: выход из каталога «/home/build/misc/map_podm/mapsoft2/modules/getopt»

...
```

**Comment by sikmir** [comment]
Yes, I have the same problem.

**Comment by slazav** [comment]
Спасибо! Вижу, что некоторые тесты не зависят явно от программ, которые используют. Есть ли что-то еще - пока не понял

**Comment by slazav** [comment]
Интересно, что эта проблема раньше не встречалась

**Comment by ioctl-user** [comment]
Насколько я знаю автоматических средств для выявления подобных неявных зависимостей нет.

Можно разве что пособирать с разными числом потоков.

**Comment by slazav** [comment]
Я попробую подумать и исправить. Там явно есть проблема, но я сходу не понимаю, как правильнее расписать зависимости. Я еще все усложнил тем, что недавно ввел таргет notests для быстрой сборки

**Comment by slazav** [comment]
Надеюсь, что исправил

**Comment by ioctl-user** [comment]
Ошибка всё ещё есть. Я обновил модули чтобы затянуть исправление, и возможно это уже что-то другое.

```
make -j 4
...

make[2]: Цель «make_nodeps» не требует выполнения команд.
g++ -std=gnu++11  -Werror=return-type -Wstrict-aliasing=2 -O2 -fPIC -g -I..    -c -o opt.test.o opt.test.cpp
g++ -std=gnu++11 -I/usr/include/libpng16 -I/usr/include/libxml2 -Werror=return-type -Wstrict-aliasing=2 -O2 -fPIC -g -I../../modules    -c -o ms2conv.o ms2conv.cpp
make[1]: *** Нет правила для сборки цели «../../modules/geo_data/geo_data.a», требуемой для «ms2conv».  Останов.
make[1]: *** Ожидание завершения заданий…
```

**Comment by slazav** [comment]
да, это уже не с тестами

**Comment by slazav** [comment]
Это, вроде, тоже исправил. Зависимости и порядок сборки модулей у меня вычисляется во внешней программе `get_deps`, потом для них вызываются  `make -C <модуль>`. Сейчас я в этот жестко заданный порядок добавил самый внешний модуль/директорию, который раньше оттуда выпадал. Распараллеливание происходит для каждого модуля отдельно, а порядок их сборки жестко задан.

**Comment by ioctl-user** [comment]
С -j 11:

```
make[2]: выход из каталога «/home/build/misc/map_podm/mapsoft2/modules/filename»
make[2]: вход в каталог «/home/build/misc/map_podm/mapsoft2/modules/tmpdir»
ar crs tmpdir.a tmpdir.o
g++   tmpdir.test.o tmpdir.o ../filename/filename.a ../err/err.a  -lzip  -o tmpdir.test
ar crs tmpdir.a tmpdir.o
/usr/bin/ld: g++   tmpdir.test.o tmpdir.o ../filename/filename.a ../err/err.a  -lzip  -o tmpdir.test
tmpdir.test.o: в функции «main.cold»:
/home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:29:(.text.unlikely+0x2d4): undefined reference to `TmpDir::~TmpDir()'
/usr/bin/ld: tmpdir.test.o: в функции «main»:
/home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:47:(.text.unlikely+0x3e3): undefined reference to `TmpDir::~TmpDir()'
/usr/bin/ld: /home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:19:(.text.startup+0x4e): undefined reference to `TmpDir::TmpDir(char const*)'
/usr/bin/ld: /home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:22:(.text.startup+0xcb): undefined reference to `TmpDir::add(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:28:(.text.startup+0x3ce): undefined reference to `TmpDir::zip(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: /home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:29:(.text.startup+0x3de): undefined reference to `TmpDir::~TmpDir()'
/usr/bin/ld: /home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:37:(.text.startup+0x3ed): undefined reference to `TmpDir::TmpDir(char const*)'
/usr/bin/ld: /home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:38:(.text.startup+0x403): undefined reference to `TmpDir::unzip(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:46:(.text.startup+0x44b): undefined reference to `TmpDir::zip(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: /home/build/misc/map_podm/mapsoft2/modules/tmpdir/tmpdir.test.cpp:47:(.text.startup+0x46b): undefined reference to `TmpDir::~TmpDir()'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make[2]: *** [<встроенное>: tmpdir.test] Ошибка 1
make[2]: выход из каталога «/home/build/misc/map_podm/mapsoft2/modules/tmpdir»
make[1]: *** [../../modules/Makefile.inc:105: make_deps] Ошибка 2
make[1]: выход из каталога «/home/build/misc/map_podm/mapsoft2/programs/ms2tiles»
make: *** [Makefile:33: ms2tiles] Ошибка 2

```

**Comment by slazav** [comment]
Прошу прощения за задержку, я был занят в выходные. Попробую сейчас разобраться.
Пока не очень понял, что тут происходит (а у меня не воспрозводится). Можно ли это воспроизвести, если зайти в каталог `modules/tmpdir` и сказать `make clean; make -j 11`?
Видно, что не находятся функции, которые должны быть в `tmpdir.o`. При этом собственно компиляции tmpdir.c -> tmpdir.o я не вижу. При этом на отсутствие .o не ругается ни `ar` ни `ld`. Не может ли быть, что в директории изначально лежит битый .o?

**Comment by ioctl-user** [comment]
Из папки modules/tmpdir не воспроизводится - собирается нормально.

Могу попробовать собрать проект в папке /tmp/ , запаковать всё что получилось и отправить на препарирование. Ну или сделать запуск сборки со strace -f , и отправить получившиеся гигабайты логов. Может быть есть и ещё как-то менее хардкорный вариант.

**Comment by slazav** [comment]
Ну, может, для начала полный лог неудачной сборки

**Comment by ioctl-user** [comment]
Сейчас похожим образом не собирается iconv.test.

Также есть странные ошибки запуска других тестов, но файлы по итогу сборки вроде бы получаются нормальные.

[log.txt](https://github.com/user-attachments/files/17799659/log.txt)

**Comment by slazav** [comment]
Кажется, я понял, что происходит не так: распараллеливается самый внешний Makefile, сборка разных программ. В результате сборка модулей запускается параллельно, без учета их зависимостей. 
Похоже, что лучше всего убрать это распараллеливание, сделать в корневом Makefile такой же жестко заданный цикл, как в programs/Makefile. Сейчас сделаю

**Comment by ioctl-user** [comment]
Похоже собирается, но в выводе много сомнительных предупреждений.
Там в конце предупреждения по Makefile, и много ещё других типов (можно найти по слову "Нет").

[log3.txt](https://github.com/user-attachments/files/17801710/log3.txt)

**Comment by slazav** [comment]
Видно, что директория с модулями не чистая (а если там все уже собрано, то и проблем с параллельной сборкой быть не должно).

У меня была идея, что из корневого makefile'а не надо отдельно собирать и чистить всю директорию с модулями (модулей может быть много, они могут быть использованы в разных проектах), так что корневого make clean недостаточно, надо make -C modules clean делать. (Но, может, это и сомнительное решение.) Сам я глобальным make clean не пользуюсь, либо собираю все в чистом окружении, либо собираю и отлаживаю отдельные части.

Предупреждения сейчас исправлю - это моя новая ошибка при переделывании makefile'ов.

**Comment by ioctl-user** [comment]
> Видно, что директория с модулями не чистая (а если там все уже собрано, то и проблем с параллельной сборкой быть не должно).

Судя по bash history, я давал команду `make clean` перед сборкой. Сейчас перепроверил, сказал:
```
make clean
make -j 11 2>&1 | tee /tmp/log.txt
```

В логе опять масса ошибок вида
```
/bin/sh: строка 1: ../../programs/ms2img/ms2img: Нет такого файла или каталога
```

См. файл  [log.txt](https://github.com/user-attachments/files/17803138/log.txt)


Возможно, make clean что-то недочищает.

**Comment by slazav** [comment]
Да, я про это и написал, что сознательно не вставлял чистку модулей в глобальный makefile.
А эти ошибки а исправил в последнем коммите в mapsoft2 (e17d0e6), почему-то он у тебя не подобрался.

**Comment by ioctl-user** [comment]
Да, не обновил вовремя.

Сейчас такого нет.

**Comment by slazav** [comment]
Ну отлично! Надеюсь, что здесь тогда все закрыто. Большое спасибо за терпение, если что-то еще будет - пиши!
